{% set name = "npy-append-array" %}
{% set version = "0.9.16" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/npy-append-array-{{ version }}.tar.gz
  sha256: 8d1b321d63d7a1c3af38d84ad139b55d1a0fe4ebb1f0d29d1d0a0c76d6fb46b5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - numpy

test:
  imports:
    - npy_append_array
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/xor2k/npy-append-array
  summary: Create Numpy `.npy` files that are larger than the main memory
  license: MIT
  license_file: LICENSE
  description: |
    Create Numpy `.npy` files that are larger than the main memory by appending
    on the zero axis.

extra:
  recipe-maintainers:
    - andife
    - xor2k
